version: '3'
services:
  db:
    image: postgres:13  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: olga
      POSTGRES_DB: yoga
    ports:
      - "5432:5432"  
    volumes:
      - ./data/db:/var/lib/postgresql/data 

